### ISSUE TITLE
Implement click on an open cell with enough flags around

### ISSUE THREAD

**Issue by adrik** [gel1os/ReactMinesweeper#3]
Clicking an open cell with a number should open unflagged neighboring cells if there is enough flagged neighbors.
For example:
1. You have a cell with a 1, and there is 3 closed cells around
2. Flag any of those cells
3. Click the cell with 1

EXR: Other 2 unflagged cells near 1-cell must open (even if there is a mine in them)

**Comment by gel1os** [comment]
Hi, that's a great suggestion, thanks!

It's done, just click on a cell with a number.
